name: 'Configure Docker Host'
description: 'Sets a DOCKER_HOST environment variable to be used for managing remote docker engines'
author: "Khaled Ezzughayyar <kz@khaledez.net>"
inputs:
  ssh-private-key:
    description: 'SSH Private Key'
    required: true
  host:
    description: 'Host IP or domain name'
    required: true
  user:
    description: 'Username on the target host that has docker privileges'
    required: true
  port:
    description: 'SSH port to use'
    required: true
    default: '22'
outputs:
  ssh-url:
    description: 'The value of the DOCKER_HOST env variable'
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/cleanup.js'
